### ISSUE TITLE
Ansible example contain not supported parameters

### ISSUE THREAD

**Issue by robertdebock** [dm-vdo/vdo#2]
When using the examples/ansible playbooks, an error is displayed.

I'm using:
```
- hosts: vdoClients
  remote_user: username
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Create VDO volume vdo1
    vdo:
      name: vdo1
      state: present
      volumegroup: VDO
      physicalsize: 260G
      logicalsize: 1T
```

The error I see:
```
#fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "Unsupported parameters for (vdo) module: physicalsize,volumegroup Supported parameters include: ackthreads,activated,biothreads,blockmapcachesize,compression,cputhreads,deduplication,device,emulate512,growphysical,indexmem,indexmode,logicalsize,logicalthreads,name,physicalthreads,readcache,readcachesize,running,slabsize,state,writepolicy"}
```

The solution is probably to update the examples. I'll make a merge-request for that later.
