### ISSUE TITLE
RHEL8 - VDO won't start and complains about ghost/non-started /dev/vdX disk

### ISSUE THREAD

**Issue by samuelfusato** [dm-vdo/vdo#40]
Hello,

I am currently unable to create vdo volumes on a RHEL8 VM. I cannot bring `vdo.service` up. Please, see below details about it:

```
[root@virtmanager-rhel8 ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.4 (Ootpa)
```
```
[root@virtmanager-rhel8 ~]# rpm -qa | grep vdo
kmod-kvdo-6.2.4.26-77.el8.x86_64
vdo-6.2.4.14-14.el8.x86_64
```
As per the below output, vdo.service fails to start complaining about a disk I have not started before (`/dev/vdb`). I have removed that disk but it keeps complaining:

```
[root@virtmanager-rhel8 ~]# systemctl status vdo
● vdo.service - VDO volume services
   Loaded: loaded (/usr/lib/systemd/system/vdo.service; enabled; vendor preset: enabled)
   Active: inactive (dead)

ago 01 00:26:58 virtmanager-rhel8 systemd[1]: Starting VDO volume services...
ago 01 00:26:58 virtmanager-rhel8 vdo[10018]: vdo: ERROR - Could not set up device mapper for vdo1
ago 01 00:26:58 virtmanager-rhel8 vdo[10018]: vdo: ERROR - vdodumpconfig: Failed to make FileLayer from '/dev/vdb' with No such file or directory
ago 01 00:26:58 virtmanager-rhel8 vdo[10018]: Starting VDO vdo1
ago 01 00:26:58 virtmanager-rhel8 vdo[10018]: ERROR - Could not set up device mapper for vdo1
ago 01 00:26:58 virtmanager-rhel8 vdo[10018]: ERROR - vdodumpconfig: Failed to make FileLayer from '/dev/vdb' with No such file or directory
ago 01 00:26:58 virtmanager-rhel8 systemd[1]: vdo.service: Main process exited, code=exited, status=1/FAILURE
ago 01 00:26:58 virtmanager-rhel8 systemd[1]: vdo.service: Failed with result 'exit-code'.
ago 01 00:26:58 virtmanager-rhel8 systemd[1]: Failed to start VDO volume services.
[root@virtmanager-rhel8 ~]#
```
```
[root@virtmanager-rhel8 ~]# lsblk 
NAME          MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sr0            11:0    1 1024M  0 rom  
vda           252:0    0   20G  0 disk 
├─vda1        252:1    0    1G  0 part /boot
└─vda2        252:2    0   19G  0 part 
  ├─rhel-root 253:0    0   17G  0 lvm  /
  └─rhel-swap 253:1    0    2G  0 lvm  [SWAP]
```
I have also noticed that the `/etc/vdoconf.yml` config file won't disappear from this directory after removing the installed packages. Here's the content of that file:

```
[root@virtmanager-rhel8 ~]# cat vdoconf.yml 
####################################################################
# THIS FILE IS MACHINE GENERATED. DO NOT EDIT THIS FILE BY HAND.
####################################################################
config: !Configuration
  vdos:
    vdo1: !VDOService
      _operationState: finished
      ackThreads: 1
      activated: enabled
      bioRotationInterval: 64
      bioThreads: 4
      blockMapCacheSize: 128M
      blockMapPeriod: 16380
      compression: enabled
      cpuThreads: 2
      deduplication: enabled
      device: /dev/vdb
      hashZoneThreads: 1
      indexCfreq: 0
      indexMemory: 0.25
      indexSparse: disabled
      indexThreads: 0
      logicalBlockSize: 4096
      logicalSize: 50G
      logicalThreads: 1
      maxDiscardSize: 4K
      name: vdo1
      physicalSize: 20G
      physicalThreads: 1
      slabSize: 2G
      uuid: null
      writePolicy: auto
  version: 538380551
```
Can you please advise?

Thanks.
